_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "catalog://ImageNetPretrained/FAIR/R-50-GN"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    NORM: "GN"
    STRIDE_IN_1X1: False
  FPN:
    NORM: "GN"
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "GN"
  ROI_MASK_HEAD:
    NORM: "GN"
SOLVER:
  # 3x schedule
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (420000, 500000)
  MAX_ITER: 540000